title: Haejoon's Blog
description: > # this means to ignore newlines until "baseurl:"
  Haejoon Choi's Blog.
  I'm a student of BCIT CST program. I changed my career from Mech. Eng. to Comp. Sci. to follow my dream.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haejoonchoi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Haejoon Choi # add your name
author-img: haejoon-choi.jpg # add your photo
about-author: BCIT CST 2nd term student. Studied 3D Printing for my master's degree.<br><br>
    Keyword : Movie geek, music lover, travel enthusiast, tech addict, starbucks barista.

twitter: # add your Twitter handle
facebook: HaejoonChoi91 # add your Facebook handle
github: haejoonchoi # add your Github handle
linkedin: HaejoonChoi # add your Linkedin handle
email: haejoonchoi@outlook.com # adtd your Email address
resume: Resume_HaejoonChoi_2019_0917.pdf # put my pdf file and the name of the file should be here

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
