title: Haejoon's Blog
description: > # this means to ignore newlines until "baseurl:"
  This is a Haejoon's Blog.
  I'm currently working at GM R&D and studying master's degree on Additive Manufacturing.
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Haejoon Choi # add your name
author-img: haejoon-choi.jpg # add your photo
about-author: |
    About me <br><br>
    I'm a master's degree student on Additive Manufacturing. <br><br>
    Keyword : Movie geek, music lover, travel enthusiast, tech addict.

twitter: # add your Twitter handle
facebook: HaejoonChoi091 # add your Facebook handle
github: gowns88 # add your Github handle
linkedin: HaejoonChoi # add your Linkedin handle
email: gowns88@unist.ac.kr # adtd your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
